sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-6
      - clang-3.8
install:
  - "test \"$CXX\" = g++ && export CXX=g++-6 || true"
  - "test \"$CXX\" = clang++ && export CXX=clang++-3.8 || true"
script:
  - make prefix=./build/install all
  - make install
  - make test
  - ./src/tests/check_version.sh
